#------------- VARIABLES -------------#
network: story
network_type: mainnet
chain_id: story-1

daemon: story
daemon_geth: story-geth

folder: '.story'
moniker: "story_main_validator"

custom_port_prefix: 45

node_version: 1.2.0
upgrade_folder: v1.2.0

#------------- CONFIGURATION  -------------#
peers: 'ef8d211e08ca33193c2dff535ec5a29902e2b3f4@story-mainnet-peer.itrocket.net:45656,670820eb8ef8d228fd560d13b633dac2760bc049@64.176.47.0:26656,773ca1c46d7f4f7311aa84b03295e4b9ea5e77cc@51.159.20.50:26656,0b6649eb6996819de4626f93018840fb876c316a@51.68.38.70:26656,9e1591134891a711091a2a0aec861113f76ad0db@95.217.196.166:26656,cd7c6eb0fab7c1aa249cd68d055e3fc5b1cc6ae9@51.222.42.212:26656,d53d3c04bb740fb37f03886861f6724223da8a02@15.235.227.25:26656,ed3f837119a7f1dbde9e7272c65f1366f294593b@5.199.164.81:27656,fb42ca6cbcd912a4690151f8fd48b41cfeb053ba@51.81.93.198:26656,f8eeca47cb53dc205d38097263d5d856250f6c62@79.127.227.195:59456,30d1128c3d53a7823fb3ba3b3d8c3e02d8bd5811@43.153.132.233:26656'
seeds: '8db87ee67cdf4c098d023e8f96d6156f098f0ae1@story-mainnet-seed.itrocket.net:45656'

config_toml: [
  { section: '',         option: 'proxy_app',         value: '"tcp://127.0.0.1:{{ custom_port_prefix }}658"'  },
  { section: 'rpc',      option: 'laddr',             value: '"tcp://127.0.0.1:{{ custom_port_prefix }}657"'  },
  { section: 'p2p',      option: 'laddr',             value: '"tcp://0.0.0.0:{{ custom_port_prefix }}656"'    },
  { section: 'p2p',      option: 'persistent_peers',  value: '"{{ peers }}"'                                  },
  { section: 'p2p',      option: 'seeds',             value: '"{{ seeds }}"'                                  },
  { section: 'instrumentation', option: 'prometheus', value: '"true"'                                         },
  { section: 'tx_index',  option: 'indexer',          value: '"null"'                                         },
]

story_toml: [
  { section: '',          option: 'engine-endpoint',  value: '"http://localhost:{{ custom_port_prefix }}551"' },
  { section: 'api',       option: 'address',          value: '"127.0.0.1:{{ custom_port_prefix }}317"'  },
]
