---
- name: download smartctl_exporter
  get_url:
    url: 'https://github.com/prometheus-community/smartctl_exporter/releases/download/v{{ smartctl_exporter_version }}/smartctl_exporter-{{ smartctl_exporter_version }}.linux-amd64.tar.gz'
    dest: '/tmp/smartctl_exporter-{{ smartctl_exporter_version }}.linux-amd64.tar.gz'
    mode: '0700'
    force: true

- name: unarchive smartctl_exporter
  unarchive:
    src: '/tmp/smartctl_exporter-{{ smartctl_exporter_version }}.linux-amd64.tar.gz'
    remote_src: yes
    dest: '/tmp'

- name: copy smartctl_exporter binary
  copy:
    src: '/tmp/smartctl_exporter-{{ smartctl_exporter_version }}.linux-amd64/smartctl_exporter'
    dest: '/usr/local/bin/'
    remote_src: true
    owner: root
    group: root
    mode: 755

- name: create smartctl_exporter systemd unit
  copy:
    src: smartctl_exporter.service
    dest: /etc/systemd/system/smartctl_exporter.service
    owner: root
    group: root
    mode: '600'

- name: start smartctl_exporter service
  systemd:
    name: smartctl_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
